model:
  base_learning_rate: 4.5e-6
  target: model.vqgan.vqgan_no_quant.VQModelNoQuant   # taming.models.vqgan_no_quant.VQModelNoQuant
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 64  # 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: model.vqgan.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

